### PR TITLE
unhanging tests

### LINKED ISSUE #29: Tests stall
When I run the test they get caught at "cleanup" test steps which are supposed to close the sbot.

The tests don't progress past the text and the test suite can't error or exit

### PR DESCRIPTION
**Pull request by mixmix**
this fixes #29 for me 

I'll be honest, I don't really understand how and when to use `setImmediate` ... but this works ?
_If someone has an idea of why sbot not quite having time to close cleanly was causing tape to get hung up I'd love to understand more._

### CODE REVIEW

**Comment by dominictarr** [comment]
it doesn't make sense that this works but the other way didn't.

Does it print the test output and just not exit?
this sounds like a mystery for [why-is-node-running](https://www.npmjs.com/package/why-is-node-running)

**Comment by mixmix** [comment]
that's a sweet tool. Here's what I see (try branch `why-is-node` to reproduce)

```bash
There are 7 handle(s) keeping the process running

# Timeout
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-db/db.js:50        - var timer = setInterval(update, 200)
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-db/index.js:25     - var db = require('./db')(join(opts.path || path, 'flume'), keys, opts)
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-db/create.js:7     - return SSB(
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-server/index.js:51 - var ssb = create(path.join(opts.path, 'db'), opts, opts.keys)

# TCPSERVERWRAP
(unknown stack trace)

# Timeout
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-db/db.js:50        - var timer = setInterval(update, 200)
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-db/index.js:25     - var db = require('./db')(join(opts.path || path, 'flume'), keys, opts)
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-db/create.js:7     - return SSB(
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-server/index.js:51 - var ssb = create(path.join(opts.path, 'db'), opts, opts.keys)

# TCPSERVERWRAP
(unknown stack trace)

# Timeout
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-db/db.js:50        - var timer = setInterval(update, 200)
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-db/index.js:25     - var db = require('./db')(join(opts.path || path, 'flume'), keys, opts)
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-db/create.js:7     - return SSB(
/home/mix/projects/SSBC/ssb-friends/node_modules/ssb-server/index.js:51 - var ssb = create(path.join(opts.path, 'db'), opts, opts.keys)

# TCPSERVERWRAP
(unknown stack trace)

# Timeout
/home/mix/projects/SSBC/ssb-friends/test/friends.js:283              - setTimeout(log, 5e3)
/home/mix/projects/SSBC/ssb-friends/node_modules/tape/lib/test.js:64 - return val.apply(self, arguments);
/home/mix/projects/SSBC/ssb-friends/node_modules/tape/lib/test.js:83 - this._cb(this);
/home/mix/projects/SSBC/ssb-friends/node_modules/tape/lib/test.js:64 - return val.apply(self, arguments);
```

**Comment by mixmix** [comment]
yeah it still happens with just one tape test on one file being run.

I think the problem is the way we're doing startup and shutdown of the server. The "cleanup" test is a hack which is not working. If you add `setTimeout(ssbServer.close, 5e3)` then everything closes down completely happily.
(ALSO, the node logger still mentions the `setInterval` is running in this happy case, so it's not the problem)

**Comment by mixmix** [comment]
It's tempting to make a verbose sbot harness which just works ... _but_ we need a generalised solution so heaps of people don't fall in this hole. I notice with this sort of test I use `scuttle-testbot` and I think I've used `tape-plus` for it's `beforeEach` and `afterEach` hooks. That's worked a charm for me

**Comment by dominictarr** [comment]
@mixmix what node version are you using? what os? debian?

If you just shift close to be after t.end() does that work?
```
t('cleanup', function (t) {
  t.end()
  sbot.close()
})
```

It should work as it is... it does work for me and [on travis too](https://travis-ci.org/ssbc/ssb-friends/builds/478528242) It is conceivable that not enough other people are running the tests (I know I run them but I don't really know)

Does anyone else have a problem? @christianbundy

**Comment by dominictarr** [comment]
also have you had this problem with any other ssb-* tests? which others have you been running?

**Comment by mixmix** [comment]
node 8.11.3
kubuntu (so yes debian base)
```js
t('cleanup', function (t) {
  t.end()
  sbot.close()
})
```
 does not work

---

I know this is annoying. I want to clarify that I'm trying to get tests running so I can write docs and add tests if it's helpful. Till I can run tests I don't want to touch anything (of the code).

**Comment by dominictarr** [comment]
hmm, unless it's something completely silly (which it could be, given that it only fails for you) is that there is something that on your system hasn't finished opening when close is called. It's weird that it would work within setImmediate though... because that is quite a narrow band of time.

**Comment by arj03** [comment]
Ill have a look this evening

**Comment by christianbundy** [comment]
I'm not having any problems with `npm test` on `master`, but it's possible that our dependencies are wonky. I've pushed a branch called `with-lockfile` that has a full dependency tree that works for me. You should be able to install the exact deps with `npm ci` and run `npm test`.

This should either resolve the problem *or* eliminate dependencies mismatch as a possible issue. Hope this helps!

**Comment by arj03** [comment]
I remember I went through all the code of ssb-server and modules used a few months back looking for these timer unref as they can keep the server running and fixed one. After that I didn't have a problem with ssb-server hanging anymore.

I'm not able to reproduce the hang here, node 10.11.

**Comment by mixmix** [comment]
OH GOD. I just nuked and installed the master branch and everything is passing for me now.

It seems like the npm gods just felt like throwing poop at me yesterday?
I _think_ that means this is a non-issue. I'm really sorry to waste everyones time if that's the case

**Comment by dominictarr** [comment]
npm is haunted, it's not your fault but you do need to chase the spirits away by `rm -rf node_modules`

btw, the first thing `npm ci` does is `rm -rf node_modules` so that happened when you installed from the lockfile.

**Pull request closed without merging**
